# Path to your Oh My Zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Igonore commands starting with a space character
setopt HIST_IGNORE_SPACE

# Reevaluate the prompt string each time it's displaying a prompt
setopt prompt_subst

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
autoload bashcompinit && bashcompinit
autoload -Uz compinit
compinit
# source <(kubectl completion zsh)

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    kubectl
)

source $ZSH/oh-my-zsh.sh

eval "$(starship init zsh)"
export STARSHIP_CONFIG=~/.config/starship/starship.toml

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

eval "$(zoxide init zsh)"

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

export FZF_COMPLETION_TRIGGER='~~'

if [[ -z $TMUX ]]; then
  tmux has-session -t dotfiles 2>/dev/null
  if [[ $? != 0 ]]; then
    tmux new -A -s dotfiles
  fi
fi
